scheduler/urls.py
from django.conf.urls import url

from scheduler import views
app_name = 'scheduler'
urlpatterns = [
            url(r'^add/$', views.add,name='add' ),
            url(r'^addreg/$', views.addreg,name='addreg' ),
            url(r'^schedule_reg/$',views.schedule_reg,name='schedule_reg'),
            url(r'^scheduledetail/(?P<buildid>\d+)$',views.scheduledetail,name='scheduledetail')

            ]

ventos/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ventos import views
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'ventos.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', 'ventos.views.index', name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^scheduler/',include('scheduler.urls'))] 

ventos/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from scheduler.forms import BuildingDataForm,RegistrationDataForm
from scheduler.models import RegDoc,BuildingDoc,buildingdata
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.template import RequestContext
import csv
import os
from scheduler.utils import read_and_filter_csv,is_whitespace

def index(request):
    return render_to_response('ventos/home.html',context_instance=RequestContext(request))

ventos/templates/ventos/base.html
{% load staticfiles %}
<html>
<head>
<link href="{% static  "images/ventos_icon.ico" %}" rel="ventos icon">
<title>VentOS</title>

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

</head>
<body>
<div class="page-header text-center">

    <img src="{% static "/images/Ventos.png" %}" alt=""/>
    <h1>VENTOS - Scheduler</h1>
</div>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
        {% block content%}
        {% endblock %}
    </div>
    </div>
</div>
</body>
</html>

ventos/templates/ventos/home.html
{% extends 'ventos/base.html' %}
{% block content %}
<p> Ventos Scheduler Home Page</p>
<div class="row">
    Step:1
            <a href="{% url 'scheduler:add' %}" class="btn btn-link" role="button">Add Building Data</a>
    </div>
    <div class="row">
        Step 2:
            <a href="{% url 'scheduler:addreg' %}" class="btn btn-link" role="button">Add Registration Data</a>
    </div>
    <div class="row">
        Step 3:
    <a href="{% url 'scheduler:schedule_reg' %}" class="btn btn-link" role="button">Schedule</a>
</div>
    <divi class="row">
    <button type="button" class="btn btn-link">Show Calendar</button>
</div>
{%endblock%}

ventos/templates/ventos/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>